#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/Lesson_9_Assignment_Data_Visualization_with_ggplot2.R /autograder/source/Lesson_9_Assignment_Data_Visualization_with_ggplot2.R

cd /autograder/source


Rscript grade_one_submission.r 
